// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { env as envFile } from '@/env/index.js'
import 'dotenv/config'
import { defineConfig, env } from 'prisma/config'

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  engine: 'classic',
  datasource: {
    url:
      envFile.NODE_ENV === 'production'
        ? env('DATABASE_URL')
        : envFile.DATABASE_URL,
  },
})
