name: Run E2E Tests

on:
  pull_request:
    branches: [main]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql:latest
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: gympass
        ports:
          - 5432:5432
        # Aguarda o banco estar pronto antes de iniciar os steps
        options: >-
          --health-cmd "pg_isready -U docker -d gympass"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v6
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24 
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run E2E Tests
        run: npm run test:e2e
        env:
          JWT_SECRET: testelouco
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/gympass?schema=public"
          NODE_ENV: test

          # Adicione estas linhas abaixo:
          CLOUDINARY_KEY: "test-key"
          CLOUDINARY_SECRET: "test-secret"
          CLOUDINARY_NAME: "test-name"
          FRONTEND_URL: "http://localhost:3000"
          NODE_ENV: test